export enum EENV_CONFIG	{
	NODE_ENV = 'NODE_ENV',

	JWT_ACCESS_SECRET = 'JWT_ACCESS_SECRET',
	JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
	JWT_ACCESS_EXPIRATION = 'JWT_ACCESS_EXPIRATION',
	JWT_REFRESH_EXPIRATION = 'JWT_REFRESH_EXPIRATION',

	GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
	GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
	GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
	OCR_API_KEY = 'OCR_API_KEY',
}